# Generated by Django 2.2.7 on 2020-03-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('esalary', models.IntegerField()),
            ],
        ),
    ]
